// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tara_tool.Data;

#nullable disable

namespace tara_tool.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260511211626_DamageScenarioUpdate2")]
    partial class DamageScenarioUpdate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("AttackPathThreatScenario", b =>
                {
                    b.Property<long>("AttackPathsId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ThreatScenariosId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AttackPathsId", "ThreatScenariosId");

                    b.HasIndex("ThreatScenariosId");

                    b.ToTable("AttackPathThreatScenario");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.Property<byte[]>("CredentialId")
                        .HasMaxLength(1024)
                        .HasColumnType("BLOB");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CredentialId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserPasskeys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("tara_tool.Data.Tables.AccessControl", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Manage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Owner")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReadAccess")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WriteAccess")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ProjectId");

                    b.ToTable("AccessControls");
                });

            modelBuilder.Entity("tara_tool.Data.Tables.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Organization")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("tara_tool.Data.Tables.Asset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("AssetNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("IdItemDefinition")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IdTag")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdItemDefinition");

                    b.HasIndex("IdTag");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("tara_tool.Data.Tables.AttackPath", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttackFeasibilityRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ElapsedTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Equipment")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KnowledgeOfComponents")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpecialistExpertise")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Value")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WindowOfOpportunity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AttackPaths");
                });

            modelBuilder.Entity("tara_tool.Data.Tables.DamageScenario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DamageScenarioNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("DamageScenarios");
                });

            modelBuilder.Entity("tara_tool.Data.Tables.Image", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("tara_tool.Data.Tables.ItemDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("IdProject")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ItemBoundaryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemBoundaryText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemFunction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("OperationalEnvironmentImageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OperationalEnvironmentText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("PreliminaryArchitectureId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreliminaryArchitectureText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("TechnicalSketchId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdProject");

                    b.HasIndex("ItemBoundaryId");

                    b.HasIndex("OperationalEnvironmentImageId");

                    b.HasIndex("PreliminaryArchitectureId");

                    b.HasIndex("TechnicalSketchId");

                    b.ToTable("ItemDefinitions");
                });

            modelBuilder.Entity("tara_tool.Data.Tables.PendingRegistration", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PendingRegistrations");
                });

            modelBuilder.Entity("tara_tool.Data.Tables.Project", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateLastChanged")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("tara_tool.Data.Tables.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("IdProject")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdProject");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("tara_tool.Data.Tables.ThreatScenario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DamageScenariosId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RiskValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StrideCategorie")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DamageScenariosId");

                    b.ToTable("ThreatScenarios");
                });

            modelBuilder.Entity("tara_tool.Data.Tables.TreatmentDecision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ImpactRatingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RiskTreatmentOption")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TreatmentDecisions");
                });

            modelBuilder.Entity("AttackPathThreatScenario", b =>
                {
                    b.HasOne("tara_tool.Data.Tables.AttackPath", null)
                        .WithMany()
                        .HasForeignKey("AttackPathsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tara_tool.Data.Tables.ThreatScenario", null)
                        .WithMany()
                        .HasForeignKey("ThreatScenariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("tara_tool.Data.Tables.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("tara_tool.Data.Tables.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.HasOne("tara_tool.Data.Tables.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Microsoft.AspNetCore.Identity.IdentityPasskeyData", "Data", b1 =>
                        {
                            b1.Property<byte[]>("IdentityUserPasskeyCredentialId");

                            b1.Property<byte[]>("AttestationObject")
                                .IsRequired();

                            b1.Property<byte[]>("ClientDataJson")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("CreatedAt");

                            b1.Property<bool>("IsBackedUp");

                            b1.Property<bool>("IsBackupEligible");

                            b1.Property<bool>("IsUserVerified");

                            b1.Property<string>("Name");

                            b1.Property<byte[]>("PublicKey")
                                .IsRequired();

                            b1.Property<uint>("SignCount");

                            b1.PrimitiveCollection<string>("Transports");

                            b1.HasKey("IdentityUserPasskeyCredentialId");

                            b1.ToTable("AspNetUserPasskeys");

                            b1.ToJson("Data");

                            b1.WithOwner()
                                .HasForeignKey("IdentityUserPasskeyCredentialId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tara_tool.Data.Tables.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("tara_tool.Data.Tables.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("tara_tool.Data.Tables.AccessControl", b =>
                {
                    b.HasOne("tara_tool.Data.Tables.ApplicationUser", "ApplicationUser")
                        .WithMany("Projects")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tara_tool.Data.Tables.Project", "Project")
                        .WithMany("Access")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("tara_tool.Data.Tables.Asset", b =>
                {
                    b.HasOne("tara_tool.Data.Tables.ItemDefinition", "ItemDefinition")
                        .WithMany("Assets")
                        .HasForeignKey("IdItemDefinition")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tara_tool.Data.Tables.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("IdTag");

                    b.Navigation("ItemDefinition");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("tara_tool.Data.Tables.DamageScenario", b =>
                {
                    b.HasOne("tara_tool.Data.Tables.Asset", "Asset")
                        .WithMany("DamageScenarios")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("tara_tool.Data.Tables.ItemDefinition", b =>
                {
                    b.HasOne("tara_tool.Data.Tables.Project", "Project")
                        .WithMany("ItemDefinitions")
                        .HasForeignKey("IdProject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tara_tool.Data.Tables.Image", "ItemBoundary")
                        .WithMany()
                        .HasForeignKey("ItemBoundaryId");

                    b.HasOne("tara_tool.Data.Tables.Image", "OperationalEnvironmentImage")
                        .WithMany()
                        .HasForeignKey("OperationalEnvironmentImageId");

                    b.HasOne("tara_tool.Data.Tables.Image", "PreliminaryArchitecture")
                        .WithMany()
                        .HasForeignKey("PreliminaryArchitectureId");

                    b.HasOne("tara_tool.Data.Tables.Image", "TechnicalSketch")
                        .WithMany()
                        .HasForeignKey("TechnicalSketchId");

                    b.Navigation("ItemBoundary");

                    b.Navigation("OperationalEnvironmentImage");

                    b.Navigation("PreliminaryArchitecture");

                    b.Navigation("Project");

                    b.Navigation("TechnicalSketch");
                });

            modelBuilder.Entity("tara_tool.Data.Tables.Tag", b =>
                {
                    b.HasOne("tara_tool.Data.Tables.Project", "Project")
                        .WithMany("Tags")
                        .HasForeignKey("IdProject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("tara_tool.Data.Tables.ThreatScenario", b =>
                {
                    b.HasOne("tara_tool.Data.Tables.DamageScenario", "DamageScenarios")
                        .WithMany("ThreatScenarios")
                        .HasForeignKey("DamageScenariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DamageScenarios");
                });

            modelBuilder.Entity("tara_tool.Data.Tables.ApplicationUser", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("tara_tool.Data.Tables.Asset", b =>
                {
                    b.Navigation("DamageScenarios");
                });

            modelBuilder.Entity("tara_tool.Data.Tables.DamageScenario", b =>
                {
                    b.Navigation("ThreatScenarios");
                });

            modelBuilder.Entity("tara_tool.Data.Tables.ItemDefinition", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("tara_tool.Data.Tables.Project", b =>
                {
                    b.Navigation("Access");

                    b.Navigation("ItemDefinitions");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
